org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.fabric-loader=0.19.2
deps.fabric-api=[VERSIONED]

# Dependency Properties
deps.jei=29.5.0.26

## Mod Properties
mod.id=blockbox
mod.name=The Block Box
mod.license=https://github.com/vectorwing/BlockBox/blob/26.1/LICENSE
mod.version=0.1.3
mod.group_id=vectorwing.blockbox
mod.authors=vectorwing
mod.description=A collection of building blocks, furniture and decorations!
publish.modrinth=UmGvBQOb
publish.curseforge=
#publish.additionalVersions=
